### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'list'

### ISSUE THREAD

**Issue by ruidazeng** [sandbornm/matcher#8]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[4], line 10
      7 part_pdf_ci=0.999
      8 confidence_bound=0.999
---> 10 run_experiment(part_type, part_dim, num_samples, meta_pdf_ci, part_pdf_ci, confidence_bound)
     12 mlflow.log_param("part_type", part_type)
     13 mlflow.log_param("part_dim", part_dim)

Cell In[1], line 156, in run_experiment(part_type, part_dim, num_samples, meta_pdf_ci, part_pdf_ci, confidence_bound)
    154 def run_experiment(part_type: str, part_dim: int, num_samples: int, meta_pdf_ci: float, part_pdf_ci: float, confidence_bound: float):
--> 156     con_parts = load_part_data(part_type)
    157     upper_collision_rate = run_meta_markov_multivariant_analysis(con_parts, part_dim, num_samples, meta_pdf_ci, part_pdf_ci, confidence_bound)
    158     print(f"Upper collision rate: {upper_collision_rate * 100}%")

Cell In[1], line 30, in load_part_data(part_type)
     27 def load_part_data(part_type: str) -> List[Part]:
     29     parts = []
---> 30     for part_dir in os.listdir(f'psig_matcher/data/{part_type}'):
     32         sensor = part_dir[1:]
     33         measurement_files = glob.glob(f'psig_matcher/data/{part_type}/{part_dir}/*.npy')

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'psig_matcher/data/CON'

**Comment by ruidazeng** [comment]
---> 67 lower, upper = compute_normal_ci(x, confidence)
     69 val = val_comp(confidence, len(x)-1)
     70 std = np.sqrt(len(x))*(upper-lower)*val

Cell In[9], line 54, in compute_normal_ci(x, confidence)
     51 def compute_normal_ci(x: List[float], confidence: float) -> Tuple[float, float]:
     52     """Computes the confidence interval for a given confidence bound."""
---> 54     if sum(x) == 0: return (0, 0)
     56     if len(x) < 30:
     57         return st.t.interval(confidence, len(x)-1, loc=np.mean(x), scale=st.sem(x))

TypeError: unsupported operand type(s) for +: 'int' and 'list'

**Comment by ruidazeng** [comment]
After some examination of the data, I found out that x, defined as List[float], is actually a nested list shown below:
 
![unnamed](https://user-images.githubusercontent.com/31152346/204941399-7ddab605-dcb1-45a5-811f-faae85678658.png)

This caused the error because the sum function could not calculate the actual sum. 
![unnamed2](https://user-images.githubusercontent.com/31152346/204941412-ab53256e-9679-46be-85bf-b5088d6674e1.png)

I did some double checking with the previous version, it seems like this line of code that checks for the sum(x) == 0 was a relatively new line and was not present in old versions. 
For now, I've made a small edit such that the sum will be summing up all the values in the nested list by flattening the list. Although I am not sure this is conceptually correct, this fixed the aforementioned bugs in the issue. 
![unnamed3](https://user-images.githubusercontent.com/31152346/204941416-95f3a432-215d-480c-8a3e-dcb5bfb2a118.png)

There are still some more bugs that I am working on but I've made progress.

**Comment by ruidazeng** [comment]
![image](https://user-images.githubusercontent.com/31152346/204946742-d3eca6e7-3e99-4d25-87b7-bed675f32f18.png)

This runs into issue when we run into x: List[float] like this. Do you know what this potentially is? And how to handle it?

**Comment by ruidazeng** [comment]
Final Update for Tonight (11/30):

![image](https://user-images.githubusercontent.com/31152346/204947424-f8eb598f-45e5-4f9e-8e60-a34a4bea1e87.png)

I used the numpy flatten to solve the issue, again I am not sure if this is correct conceptually, but it does work.

![image](https://user-images.githubusercontent.com/31152346/204947485-42b3b53a-7e39-4851-a0de-c89dad3728b3.png)

This is the current result for the base, integrated with MLFLOW tracking with the same warning (which also occurred in the process_validation)

**Comment by ruidazeng** [comment]
Also a note and a valuable lesson: Always restart the entire kernel in the case of MLFlow otherwise Jupyter would be unable to find the experiment ID

**Comment by ruidazeng** [comment]
Also let me know if there's anything about the warning or should I ignore it and proceed

**Comment by henrygilbert22** [comment]
Change sum to np.mean
